name: sevenminuteswiththelord
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.0.0
  audioplayers: ^5.1.0
  flutter_local_notifications: ^16.1.0
  permission_handler: ^11.2.0
  intl: ^0.18.1
  intl_utils: ^2.8.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/mixkit-alert-quick-chime-766.wav
  generate: true

flutter_intl:
  enabled: true
  output_dir: lib/generated # The directory where files should be generated.
  arb_dir: lib/l10n # The directory containing your ARB files.
